#!/usr/bin/env python3
"""
Script to update API Gateway environment variables with actual service URLs
Run this after deploying all services to Render.com
"""

import os
import sys
from pathlib import Path

def update_env_file():
    """Update the API Gateway .env file with production service URLs"""
    
    print("Car Rental API Gateway - Environment Update Script")
    print("=" * 50)
    
    # Get service URLs from user
    services = {
        'USER_SERVICE_URL': 'user-service',
        'VEHICLE_SERVICE_URL': 'vehicle-service', 
        'RENTAL_SERVICE_URL': 'rental-service',
        'PAYMENT_SERVICE_URL': 'payment-service',
        'ADMIN_SERVICE_URL': 'admin-service',
        'CHAT_SERVICE_URL': 'chat-service',
        'RATING_SERVICE_URL': 'rating-service'
    }
    
    service_urls = {}
    
    print("Enter the actual service URLs from Render.com:")
    print("(Format: https://service-name.onrender.com)")
    print()
    
    for env_var, service_name in services.items():
        while True:
            url = input(f"Enter URL for {service_name}: ").strip()
            if url.startswith('https://') and '.onrender.com' in url:
                service_urls[env_var] = url
                break
            else:
                print("❌ Invalid URL format. Please use: https://service-name.onrender.com")
    
    # Get frontend URL
    while True:
        frontend_url = input("Enter Frontend URL: ").strip()
        if frontend_url.startswith('https://'):
            break
        else:
            print("❌ Invalid URL format. Please use: https://your-frontend.com")
    
    # Create production environment file
    api_gateway_dir = Path(__file__).parent.parent / 'api-gateway'
    env_file = api_gateway_dir / '.env.production'
    
    env_content = f"""# Production Environment Configuration
# Generated by update-api-gateway-env.py

# API Gateway Configuration
PORT=10000
API_VERSION=1.0.0
ENVIRONMENT=production
LOG_LEVEL=INFO

# Security
JWT_SECRET_KEY=your-production-jwt-secret
RATE_LIMIT_MAX_REQUESTS=300
RATE_LIMIT_WINDOW_SECONDS=60

# Service URLs
{service_urls['USER_SERVICE_URL'].replace('USER_SERVICE_URL=', 'USER_SERVICE_URL=')}
{service_urls['VEHICLE_SERVICE_URL'].replace('VEHICLE_SERVICE_URL=', 'VEHICLE_SERVICE_URL=')}
{service_urls['RENTAL_SERVICE_URL'].replace('RENTAL_SERVICE_URL=', 'RENTAL_SERVICE_URL=')}
{service_urls['PAYMENT_SERVICE_URL'].replace('PAYMENT_SERVICE_URL=', 'PAYMENT_SERVICE_URL=')}
{service_urls['ADMIN_SERVICE_URL'].replace('ADMIN_SERVICE_URL=', 'ADMIN_SERVICE_URL=')}
{service_urls['CHAT_SERVICE_URL'].replace('CHAT_SERVICE_URL=', 'CHAT_SERVICE_URL=')}
{service_urls['RATING_SERVICE_URL'].replace('RATING_SERVICE_URL=', 'RATING_SERVICE_URL=')}

# CORS Settings
FRONTEND_URL={frontend_url}
ADDITIONAL_CORS_ORIGINS={frontend_url}
"""

    # Write the environment variables in the correct format
    with open(env_file, 'w') as f:
        f.write("# Production Environment Configuration\n")
        f.write("# Generated by update-api-gateway-env.py\n\n")
        f.write("# API Gateway Configuration\n")
        f.write("PORT=10000\n")
        f.write("API_VERSION=1.0.0\n")
        f.write("ENVIRONMENT=production\n")
        f.write("LOG_LEVEL=INFO\n\n")
        f.write("# Security\n")
        f.write("JWT_SECRET_KEY=your-production-jwt-secret\n")
        f.write("RATE_LIMIT_MAX_REQUESTS=300\n")
        f.write("RATE_LIMIT_WINDOW_SECONDS=60\n\n")
        f.write("# Service URLs\n")
        for env_var, url in service_urls.items():
            f.write(f"{env_var}={url}\n")
        f.write(f"\n# CORS Settings\n")
        f.write(f"FRONTEND_URL={frontend_url}\n")
        f.write(f"ADDITIONAL_CORS_ORIGINS={frontend_url}\n")
    
    print(f"\n✅ Environment file created: {env_file}")
    print("\n📋 Copy these environment variables to your Render.com API Gateway service:")
    print("-" * 70)
    
    with open(env_file, 'r') as f:
        for line in f:
            if line.strip() and not line.startswith('#'):
                print(line.strip())
    
    print("-" * 70)
    print("\n⚠️  Don't forget to:")
    print("1. Update JWT_SECRET_KEY with a secure random string")
    print("2. Apply these variables in Render.com dashboard")
    print("3. Restart the API Gateway service after updating")

if __name__ == "__main__":
    try:
        update_env_file()
    except KeyboardInterrupt:
        print("\n\n❌ Script cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
